#!/usr/bin/env bash
# Script that displays information about subdomains

# Function to get subdomain info
get_subdomain_info() {
    local domain=$1
    local subdomain=$2

    info=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print}')
    record_type=$(echo $info | awk '{print $4}')
    destination=$(echo $info | awk '{print $5}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    # No subdomain provided, display all default subdomains
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info "$domain" "$sub"
    done
else
    # Specific subdomain provided
    get_subdomain_info "$domain" "$subdomain"
fi
